export interface Song {
  id: string;
  createdAt: Date;
  publishedAt: Date | null;
  name: string;
  language: string;
  uploader: string;
  artistName: string;
  genre: string;
  lyrics: string;
  translationLanguage: string | null;
  translatedName: string | null;
  translatedLyrics: string | null;
  poster: string;
}

export const mockSongs: Song[] = [
  {
    id: "1",
    createdAt: new Date("2026-01-15T10:30:00"),
    publishedAt: new Date("2026-01-16T14:00:00"),
    name: "Bohemian Rhapsody",
    language: "English",
    uploader: "john.doe@email.com",
    artistName: "Queen",
    genre: "Rock",
    lyrics: "Is this the real life? Is this just fantasy?\nCaught in a landslide, no escape from reality\nOpen your eyes, look up to the skies and see\nI'm just a poor boy, I need no sympathy",
    translationLanguage: "Spanish",
    translatedName: "Rapsodia Bohemia",
    translatedLyrics: "¿Es esta la vida real? ¿Es solo fantasía?\nAtrapado en un derrumbe, sin escape de la realidad",
    poster: "https://picsum.photos/seed/bohemian/400/400",
  },
  {
    id: "2",
    createdAt: new Date("2026-01-18T09:15:00"),
    publishedAt: null,
    name: "Imagine",
    language: "English",
    uploader: "jane.smith@email.com",
    artistName: "John Lennon",
    genre: "Pop",
    lyrics: "Imagine there's no heaven\nIt's easy if you try\nNo hell below us\nAbove us, only sky",
    translationLanguage: "French",
    translatedName: "Imagine",
    translatedLyrics: "Imagine qu'il n'y a pas de paradis\nC'est facile si tu essaies",
    poster: "https://picsum.photos/seed/imagine/400/400",
  },
  {
    id: "3",
    createdAt: new Date("2026-01-20T16:45:00"),
    publishedAt: new Date("2026-01-21T10:00:00"),
    name: "La Vie en Rose",
    language: "French",
    uploader: "pierre.martin@email.com",
    artistName: "Édith Piaf",
    genre: "Jazz",
    lyrics: "Quand il me prend dans ses bras\nIl me parle tout bas\nJe vois la vie en rose",
    translationLanguage: "English",
    translatedName: "Life in Pink",
    translatedLyrics: "When he takes me in his arms\nHe speaks to me softly\nI see life in pink",
    poster: "https://picsum.photos/seed/lavie/400/400",
  },
  {
    id: "4",
    createdAt: new Date("2026-01-22T11:20:00"),
    publishedAt: null,
    name: "Despacito",
    language: "Spanish",
    uploader: "maria.garcia@email.com",
    artistName: "Luis Fonsi",
    genre: "Pop",
    lyrics: "Sí, sabes que ya llevo un rato mirándote\nTengo que bailar contigo hoy\nVi que tu mirada ya estaba llamándome",
    translationLanguage: "English",
    translatedName: "Slowly",
    translatedLyrics: "Yes, you know I've been looking at you for a while\nI have to dance with you today",
    poster: "https://picsum.photos/seed/despacito/400/400",
  },
  {
    id: "5",
    createdAt: new Date("2026-01-23T08:00:00"),
    publishedAt: new Date("2026-01-24T09:30:00"),
    name: "99 Luftballons",
    language: "German",
    uploader: "hans.mueller@email.com",
    artistName: "Nena",
    genre: "Pop",
    lyrics: "Hast du etwas Zeit für mich?\nDann singe ich ein Lied für dich\nVon 99 Luftballons",
    translationLanguage: "English",
    translatedName: "99 Red Balloons",
    translatedLyrics: "Do you have some time for me?\nThen I'll sing a song for you\nAbout 99 balloons",
    poster: "https://picsum.photos/seed/luftballons/400/400",
  },
  {
    id: "6",
    createdAt: new Date("2026-01-25T14:30:00"),
    publishedAt: null,
    name: "Gangnam Style",
    language: "Korean",
    uploader: "kim.lee@email.com",
    artistName: "PSY",
    genre: "Pop",
    lyrics: "오빤 강남스타일\n강남스타일\n낮에는 따사로운 인간적인 여자",
    translationLanguage: "English",
    translatedName: "Gangnam Style",
    translatedLyrics: "Oppa is Gangnam style\nGangnam style\nA girl who is warm during the day",
    poster: "https://picsum.photos/seed/gangnam/400/400",
  },
  {
    id: "7",
    createdAt: new Date("2026-01-26T10:15:00"),
    publishedAt: new Date("2026-01-27T11:00:00"),
    name: "Bella Ciao",
    language: "Italian",
    uploader: "marco.rossi@email.com",
    artistName: "Traditional",
    genre: "Folk",
    lyrics: "Una mattina mi son svegliato\nO bella ciao, bella ciao, bella ciao ciao ciao\nUna mattina mi son svegliato\nE ho trovato l'invasor",
    translationLanguage: "English",
    translatedName: "Goodbye Beautiful",
    translatedLyrics: "One morning I woke up\nOh goodbye beautiful, goodbye beautiful, goodbye beautiful\nOne morning I woke up\nAnd I found the invader",
    poster: "https://picsum.photos/seed/bellaciao/400/400",
  },
  {
    id: "8",
    createdAt: new Date("2026-01-27T15:45:00"),
    publishedAt: null,
    name: "Sukiyaki",
    language: "Japanese",
    uploader: "yuki.tanaka@email.com",
    artistName: "Kyu Sakamoto",
    genre: "Pop",
    lyrics: "上を向いて歩こう\n涙がこぼれないように\n思い出す春の日",
    translationLanguage: "English",
    translatedName: "I Look Up as I Walk",
    translatedLyrics: "I look up as I walk\nSo the tears won't fall\nRemembering those spring days",
    poster: "https://picsum.photos/seed/sukiyaki/400/400",
  },
  {
    id: "9",
    createdAt: new Date("2026-01-28T09:30:00"),
    publishedAt: new Date("2026-01-29T10:00:00"),
    name: "Katyusha",
    language: "Russian",
    uploader: "ivan.petrov@email.com",
    artistName: "Traditional",
    genre: "Folk",
    lyrics: "Расцветали яблони и груши\nПоплыли туманы над рекой\nВыходила на берег Катюша",
    translationLanguage: "English",
    translatedName: "Katyusha",
    translatedLyrics: "Apple and pear trees were blooming\nMist was floating over the river\nKatyusha came out onto the bank",
    poster: "https://picsum.photos/seed/katyusha/400/400",
  },
  {
    id: "10",
    createdAt: new Date("2026-01-29T12:00:00"),
    publishedAt: null,
    name: "Ai Se Eu Te Pego",
    language: "Portuguese",
    uploader: "carlos.silva@email.com",
    artistName: "Michel Teló",
    genre: "Pop",
    lyrics: "Nossa, nossa\nAssim você me mata\nAi se eu te pego, ai ai se eu te pego",
    translationLanguage: "English",
    translatedName: "Oh If I Catch You",
    translatedLyrics: "Wow, wow\nYou're killing me like this\nOh if I catch you, oh oh if I catch you",
    poster: "https://picsum.photos/seed/aiseeu/400/400",
  },
  {
    id: "11",
    createdAt: new Date("2026-01-30T08:45:00"),
    publishedAt: new Date("2026-01-30T14:00:00"),
    name: "Hotel California",
    language: "English",
    uploader: "mike.wilson@email.com",
    artistName: "Eagles",
    genre: "Rock",
    lyrics: "On a dark desert highway, cool wind in my hair\nWarm smell of colitas, rising up through the air\nUp ahead in the distance, I saw a shimmering light",
    translationLanguage: null,
    translatedName: null,
    translatedLyrics: null,
    poster: "https://picsum.photos/seed/hotelca/400/400",
  },
  {
    id: "12",
    createdAt: new Date("2026-01-31T07:30:00"),
    publishedAt: null,
    name: "Stairway to Heaven",
    language: "English",
    uploader: "sarah.jones@email.com",
    artistName: "Led Zeppelin",
    genre: "Rock",
    lyrics: "There's a lady who's sure all that glitters is gold\nAnd she's buying a stairway to heaven\nWhen she gets there she knows, if the stores are all closed",
    translationLanguage: "German",
    translatedName: "Treppe zum Himmel",
    translatedLyrics: "Es gibt eine Dame, die sicher ist, dass alles, was glitzert, Gold ist\nUnd sie kauft eine Treppe zum Himmel",
    poster: "https://picsum.photos/seed/stairway/400/400",
  },
];
